### ISSUE TITLE
EV: Ep 84  GSF Backstage 1 w/ Chris Skipper, TOSS Project

### ISSUE THREAD

**Issue by sonicfutures** [Green-Software-Foundation/env-var-podcast#10]
- Guest(s): **Chris Skipper, TOSS Project**
- Record By: **27/09/2024**
- Publication: **10/10/2024**
- Topic:  **GSF Backstage 1**

> Contact History:

- Will contact everyone properly on **24/05/2024** spoke to Russ might be a good idea to have a first backstage episode about how **Carbon Hack 24**?
- Email sent on **30/05/2024**
- **PUBLICATION DATE** has been pushed to 8th of August to help with gathering materials.
- **PUBLICATION DATE** has been pushed back again to 22nd of August to help with gathering materials.
- Got in touch with Sean and he has pointed me in the direction of Pindy and Sean for gathering materials for this. Email sent to both on **12/08/2024**
- No response as of **19/08/2024** will send a nudge through email (sent on 19/08/2024).
- Response received from **Pindy** and email sent back to try and confirm 1-to-1 meeting with her on **27 August 2024**
- Had a short chat with Pindy Bhullar and got some info about the project. She will provide soundbytes by **27/09/2024** - will follow this up.

> Script:
https://docs.google.com/document/d/1ZNdmnEfxfGxYPL5CbNECn3yfzbwZJgnguInnczPEI1s/edit?usp=drivesdk

> Riverside Link:
[]

> Google Drive Folder:
https://drive.google.com/drive/folders/1uBigKccCWYo914lyaEv7gJBu7FatSlOH

> Marketing Folder (Snippets + Transcript):
https://drive.google.com/drive/folders/1hQ13xb--KlaQTUJ2TGhCphWXD0N6O5Tu

**Comment by sonicfutures** [comment]
> [@NAMRATA-WOKE](https://github.com/NAMRATA-WOKE) [@russelltrow](https://github.com/russelltrow) would you guys be keen on recording the first episode of Backstage with either me or Chris Adams. It will be a general round up of Carbon Hack 24 and then maybe a focus on some interesting projects from the GSF in a sort of announcement style episode.
> 
> It will need max 1 hour of your time. Is there a time date and time that suits either of you this week or next please?

@NAMRATA-WOKE @russelltrow Hey guys any thoughts on a date to record the first episode for this? Or perhaps we can nominate someone else if you're too busy? Hope you got my email last week :) Thanks!

**Comment by russelltrow** [comment]
Hey @sonicfutures I have availability next week to get involved. As a podcast newbie what is required of me and how can I prepare?

**Comment by sonicfutures** [comment]
@russelltrow Awesome. What days work for you this week?

Nothing much at the moment! I'm happy to guide you guys through it. Will get more of the script up and running from tomorrow.

**Comment by bryaki02** [comment]
Can we update the dates to:

Record By: 24/06/2024
Publication: 08/07/2024

Let me know if that works @sonicfutures

**Comment by sonicfutures** [comment]
@bryaki02 It totally works for me. Does it work for @russelltrow or @NAMRATA-WOKE can we throw out some dates to record this one please?

**Comment by sonicfutures** [comment]
Also @bryaki02 just FYI publications are always a Thursday. So I suppose this one would be **04/07/2024** for publication.

**Comment by bryaki02** [comment]
> Also @bryaki02 just FYI publications are always a Thursday. So I suppose this one would be **04/07/2024** for publication.

Great! Will keep that in mind.

**Comment by bryaki02** [comment]
@sonicfutures I had a 1:1 with Namrata yesterday after our meeting, and we discussed the first GSF Backstage episode and I wanted to support getting the ball rolling. Namrata's ideas I have captured below. Could @NAMRATA-WOKE and @russelltrow connect with @sonicfutures to find a time to meet? Ideally before the end of next week?

Overall we want to make sure each episode includes: key messaging, builds intimacy with the audience, and demonstrates the value and personality of GSF. 
Some questions/direction for Episode 1:
- What kind of organization is the GSF? We can then build on this for each episode, and when we talk more specifically about the work and projects, listeners will have greater context. 
- How does culture show up in the work that we do?
- How does the GSF work? (Members, volunteers, contributors etc.)
- What new initiatives is the GSF launching? (This would likely be for future episodes). 

@russelltrow @sonicfutures let me know your thoughts, and then we can also start framing out future GSF Backstage episodes as well. @jawache

**Comment by sonicfutures** [comment]
@bryaki02 Sounds great! @NAMRATA-WOKE @russelltrow please find a time on my calendar [here](https://www.calendly.com/sonic-futures)

This direction is great and will add these questions to the script.

**Comment by NAMRATA-WOKE** [comment]
@sonicfutures Calendly link is not working. I get a 404 error.

**Comment by sonicfutures** [comment]
> @sonicfutures Calendly link is not working. I get a 404 error.

@NAMRATA-WOKE I see you managed to book a time - thanks!

**Comment by sonicfutures** [comment]
@russelltrow Sent you an invite to a potential recording date for the first episode of Backstage on the 9th of July. I think it’s at 10pm BST so might be a bit unreasonable. Just let me know if that doesn’t work and I’ll try and arrange a time between you, myself and Namrata :)

**Comment by bryaki02** [comment]
@sonicfutures We had an internal meeting yesterday to strategize about GSF Backstage and are pivoting a bit. I will schedule time with you the week I am back, July 8th, to give an update and get your insights and thoughts. We are thinking small bite size episodes, a quick run down of a project, about 3 minutes long, instead of a full episode. I can then support, alongside @NAMRATA-WOKE and @russelltrow with identifying projects and the information to share. Thus, we will hold off on this episode and likely pivot. Will circle back to this the week of July 8th, thank you for your patience Chris!

**Comment by sonicfutures** [comment]
@bryaki02 Ok no problem at all. I think that's a great idea. Happy to flesh this idea out more!

**Comment by sonicfutures** [comment]
@NAMRATA-WOKE @russelltrow @bryaki02 So I've updated this one so we can record something by the end of July. Aiming to publish on **August 1**. Let me know if that works for you guys :)

**Comment by sonicfutures** [comment]
Had a very fruitful discussion with @bryaki02 today (**10/07/24**)how this format can be a collection of soundbytes that intersperse a script that outlines the projects read by me. This will definitely work going forward.

**Comment by bryaki02** [comment]
@NAMRATA-WOKE @russelltrow Can we identify a process to select projects that we want to highlight in the 3 minute backstage episodes? We originally suggested we would use this as a reward system to give the projects airtime that are progressing. Ideally we want to submit the first script to @sonicfutures by the end of the month, early August if this is not feasible. He can also reach out to the project lead directly to add a sound bite from them for the episode. 

For next steps I would recommend we identify by end of August the next few projects to add to the calendar for all upcoming 2024 GSF Backstage episodes. Let me know if this makes sense! @jawache

**Comment by NAMRATA-WOKE** [comment]
Perhaps:

TOSS (we can talk about the design of the workshops and how they're going, and perhaps next steps) 
RTC (evolving into a dataset and how that came about) 
IF (expansion Joseph and Asim want to talk about) 

@seanmcilroy29 do you think we’ll be able to talk about how we’re approaching the SCI for AI?

**Comment by bryaki02** [comment]
> Perhaps:
> 
> TOSS (we can talk about the design of the workshops and how they're going, and perhaps next steps) RTC (evolving into a dataset and how that came about) IF (expansion Joseph and Asim want to talk about)
> 
> @seanmcilroy29 do you think we’ll be able to talk about how we’re approaching the SCI for AI?

Thanks @NAMRATA-WOKE - if we start with TOSS @russelltrow would you be able to add some content for the script for Chris and maybe you could offer a soundbite or the project lead?

**Comment by sonicfutures** [comment]
@bryaki02 @russelltrow  @NAMRATA-WOKE 
So I've done a quick overview with some guidelines on what people could potentially talk about within the script here:
https://docs.google.com/document/d/1ZNdmnEfxfGxYPL5CbNECn3yfzbwZJgnguInnczPEI1s/edit

Please feel free to edit as you see fit!

**Comment by bryaki02** [comment]
> @bryaki02 @russelltrow @NAMRATA-WOKE So I've done a quick overview with some guidelines on what people could potentially talk about within the script here: https://docs.google.com/document/d/1ZNdmnEfxfGxYPL5CbNECn3yfzbwZJgnguInnczPEI1s/edit
> 
> Please feel free to edit as you see fit!

This is great @sonicfutures what would you need from us to use the first episode to talk about TOSS? @russelltrow would you be able to add-in here? I think we can use ads to talk about events or if we want to plug Summit or other programming we can send some information for this to be plugged in. 

This was @NAMRATA-WOKE suggestion "TOSS (we can talk about the design of the workshops and how they're going, and perhaps next steps)".

**Comment by NAMRATA-WOKE** [comment]
> > @bryaki02 @russelltrow @NAMRATA-WOKE So I've done a quick overview with some guidelines on what people could potentially talk about within the script here: https://docs.google.com/document/d/1ZNdmnEfxfGxYPL5CbNECn3yfzbwZJgnguInnczPEI1s/edit
> > Please feel free to edit as you see fit!
> 
> This is great @sonicfutures what would you need from us to use the first episode to talk about TOSS? @russelltrow would you be able to add-in here? I think we can use ads to talk about events or if we want to plug Summit or other programming we can send some information for this to be plugged in.
> 
> This was @NAMRATA-WOKE suggestion "TOSS (we can talk about the design of the workshops and how they're going, and perhaps next steps)".

Looks great to me @sonicfutures

**Comment by russelltrow** [comment]
@bryaki02 we wont have anything concrete to report specifically from the TOSS workshops until after the wrap-up session on 16th August. We could talk about the design of the workshops but it's not very interesting unless we can also share some positive outcomes.

You could talk more broadly about the status of TOSS, where it has got to so far, why it's kicked off workshops. That could then mention the workshops and setup something later that goes into more detail. @seanmcilroy29 would be the person to support that.

**Comment by NAMRATA-WOKE** [comment]
@bryaki02 @sonicfutures proposed some changes to the intro script.

**Comment by sonicfutures** [comment]
@bryaki02 @russelltrow If you could point me in the direction of who to reach out to regarding projects I'm happy to chat to these people directly about getting sound bites. Please let me know if you have any prime candidates.

**Comment by bryaki02** [comment]
> @bryaki02 @russelltrow If you could point me in the direction of who to reach out to regarding projects I'm happy to chat to these people directly about getting sound bites. Please let me know if you have any prime candidates.

@sonicfutures I will reach out to Sean and revert back to you.

**Comment by sonicfutures** [comment]
This episode is out and published! https://podcasts.castplus.fm/e/18pvvll8-backstage-toss-project
