### ISSUE TITLE
EV: Ep 72 TWiGS w/ Chris Adams & Asim Hussain

### ISSUE THREAD

**Issue by sonicfutures** [Green-Software-Foundation/env-var-podcast#11]
- Guest(s): ****
- Record By: **31/05/2024**
- Publication: **06/06/2024**
- Topic:  **TWiGS**

> Contact History:

- Participants contacted via email/slack on

> Script:
https://docs.google.com/document/d/1D6Z2iuRAMuV4G0vuNTJE2aXq5FzJkp5ulCZ4ePpVvFU

> Riverside Link:
[]

> Google Drive Folder:
https://drive.google.com/drive/folders/1I6pkEZ7zjstumAYgN2TtSPPHg9O3ccJ2

> Marketing Folder (Snippets + Transcript):
https://drive.google.com/drive/folders/1jJsA9G68KTgF_-0HBCNhLFKQlI1IWPEu

**Comment by mrchrisadams** [comment]
Hey @sonicfutures I've spoke to @jawache towards the end of May and we were able to set a few recurring dates to make sure he's available.

The first date was 9:30 MGT / 10:30 CET on Wednesday 12th June. There's space to add a third person each time, and maybe a fourth to the call.

**Comment by sonicfutures** [comment]
Awesome thanks @mrchrisadams & @jawache!

What are the other recurring dates? Would be cool to add them into the calendar. I will update the script on this episode if you want to use this one to record next week :)

**Comment by mrchrisadams** [comment]
@sonicfutures I've added you to the recurring event on the 28th June, and the 14th.

@jawache I've added a slot at between 10am and 11am on the Friday, as I think that's when you're often free, but I generally can move things around that day, so a recurring afternoon slot works would work as well.

To make this clear - I see these as "open invite" sessions, so I think it's totally ok to invite others to join these sessions (this is sort of the point of them!), but we should probably try to cap them at something like 4 people on the recording to give everyone a chance to say something.

**Comment by jawache** [comment]
Thanks @mrchrisadams agreed, i'm good with the above.

**Comment by sonicfutures** [comment]
Awesome @mrchrisadams thanks so much. Will you be using this script for your recording on the 12th? https://docs.google.com/document/d/1D6Z2iuRAMuV4G0vuNTJE2aXq5FzJkp5ulCZ4ePpVvFU

Or should I draft up something new for you guys?

**Comment by mrchrisadams** [comment]
Hi @sonicfutures thanks for sharing the script - there's no need to draft one up. 

@jawache here's the link for this TWiGs episode - https://riverside.fm/studio/ev-twigs-72--asim-and-chris?t=7d80faef18cdb6e7702a

**Comment by bryaki02** [comment]
@sonicfutures I am updating each episode so the Start is the "Record By" and the Due Date as "Publication" - can you tag me when there are updated dates for this episode? Thanks!

**Comment by sonicfutures** [comment]
@bryaki02 Sure thing! This one has already been published! https://podcasts.bcast.fm/e/x8149q5n-the-week-in-green-software-carbon-hack-24-recap
