### ISSUE TITLE
EV: Ep 77 Environment Variables  w/ Chris Adams & Romain Jacob

### ISSUE THREAD

**Issue by sonicfutures** [Green-Software-Foundation/env-var-podcast#7]
EV: Ep 77 Environment Variables  w/ Romain Jacob

- Guest(s): **Romain Jacob**
- Record By: **12/08/2024**
- Publication: **25/07/2024**
- Topic:  **Romain's talk at HotCarbon**

> Contact History:

- Romain and Chris have been in touch via email since 22/07. 

> Script:
https://docs.google.com/document/d/1h9-f-IwQKsSo5bE5or6h_jdvBuApqoKCdQ_4VImGNyM/edit?usp=drivesdk

> Riverside Link:
[LINK](https://riverside.fm/studio/ev-ep-79---romain-jacob-and-hypnos?t=fe6703350f69eaa2033b)

> Google Drive Folder:
https://drive.google.com/drive/folders/1HnQyLVGzoXtLxgRinA-S1j_q7UBuKoGY

> Marketing Folder (Snippets + Transcript):
https://drive.google.com/drive/folders/1yaVZp48zIUpmKcnnIZvHo9O5esx1JloH

**Comment by mrchrisadams** [comment]
I've created this script for the call with Romain Jacob for Wednesday 25th

https://docs.google.com/document/d/1Xuhd7jEundsb0l3cZs5pd6Vgkt-BN6rstqXmyjxrr78/edit

**Comment by sonicfutures** [comment]
@mrchrisadams Awesome thank you! I've requested access to the script. Will copy any links you drop in there over to the final publication. Also just a reminder if you get the chance to record the new intro that would be very handy please:
https://docs.google.com/document/d/1h7uK-LQdeU8gja-ZujeBRPRuJJGmdob5R1PdvbUraxs/edit?usp=sharing

**Comment by sonicfutures** [comment]
This episode has been published:
https://podcast.greensoftware.foundation/e/08j02v38-a-greener-internet-that-sleeps-more

https://youtu.be/h_0f2B3Kp_U?si=yQp6_oFVjSkbzg2a
